/*
 * hal_stm32.cpp — STM32F4 HAL implementation for DANA Mower
 *
 * Target: STM32 Nucleo-F401RE (STM32F401RET6)
 * Toolchain: STM32CubeIDE or PlatformIO with stm32cube framework
 *
 * ─── PREREQUISITE: CUBEMX PERIPHERAL INIT ──────────────────────────────────
 *
 * This file calls STM32 HAL functions that require peripherals to be initialized
 * BEFORE hal_init() runs. CubeMX generates that initialization automatically.
 * The generated code lives in Core/Src/main.c (not this file).
 *
 * Required CubeMX settings (summary — see pins_stm32.h for full table):
 *   ADC1   : PA0 (IN0) + PA1 (IN1), polling mode, resolution 12-bit
 *   TIM3   : PWM Generation CH1 (PB4, AF2) + CH2 (PB5, AF2)
 *            Prescaler = 83, Period = 999 → 1 kHz PWM at 84 MHz APB1
 *   USART2 : PA2/PA3, 115200 baud (optional, for debug prints)
 *   GPIO   : See pins_stm32.h for all PORT/PIN assignments
 *
 * ─── EXTERN HANDLES ─────────────────────────────────────────────────────────
 *
 * CubeMX declares the peripheral handles in main.c/main.h.
 * We declare them extern here so this file can use them without including
 * the entire CubeMX generated project.
 */

#include "hal_stm32.h"
#include "pins_stm32.h"

// Peripheral handles generated by CubeMX (defined in Core/Src/main.c).
// If CubeMX names them differently in your project, update these declarations.
extern ADC_HandleTypeDef  hadc1;    // ADC for joystick
extern TIM_HandleTypeDef  htim3;    // Timer for motor PWM output

// ─────────────────────────────────────────────────────────────────────────────
// File-private helpers
// ─────────────────────────────────────────────────────────────────────────────

/*
 * adc_read_channel(channel)
 *
 * Reconfigures ADC1 to sample one channel, starts a single conversion in
 * polling mode, waits for completion, and returns the 12-bit result (0–4095).
 *
 * WHY NOT JUST USE analogRead() LIKE ARDUINO?
 *   STM32 HAL does not provide a single analogRead() helper. You must:
 *     1. Set up the channel configuration (ADC_ChannelConfTypeDef)
 *     2. Call HAL_ADC_ConfigChannel() to apply it
 *     3. Start the ADC (HAL_ADC_Start)
 *     4. Wait for conversion (HAL_ADC_PollForConversion)
 *     5. Read the result (HAL_ADC_GetValue)
 *
 * FUTURE OPTIMIZATION:
 *   Polling blocks the CPU for ~1 µs per conversion. For a 10 ms loop that
 *   is negligible. If you add more ADC channels or tighten loop timing,
 *   switch to DMA-mode continuous scan: CubeMX sets this up automatically
 *   and the result buffer is always fresh without any CPU involvement.
 */
static uint32_t adc_read_channel(uint32_t channel) {
    ADC_ChannelConfTypeDef cfg = {};
    cfg.Channel      = channel;
    cfg.Rank         = 1;
    cfg.SamplingTime = ADC_SAMPLETIME_56CYCLES;   // ~0.67 µs at 84 MHz
    HAL_ADC_ConfigChannel(&hadc1, &cfg);

    HAL_ADC_Start(&hadc1);
    HAL_ADC_PollForConversion(&hadc1, 10);         // 10 ms timeout
    uint32_t result = HAL_ADC_GetValue(&hadc1);
    HAL_ADC_Stop(&hadc1);
    return result;
}

/*
 * normalizeJoystick(rawADC)
 *
 * Converts a 12-bit ADC reading (0–4095) to a normalized float (-1.0 .. +1.0)
 * with center-deadband filtering. Identical logic to the Arduino version but
 * scaled to 12-bit range (STM32_ADC_CENTER = 2048, vs Arduino's 512).
 */
static float normalizeJoystick(uint32_t rawADC) {
    int centered = (int)rawADC - STM32_ADC_CENTER;

    if (centered > -STM32_ADC_DEADBAND && centered < STM32_ADC_DEADBAND) {
        return 0.0f;
    }

    float normalized = (float)centered / (float)STM32_ADC_MAX;

    // clamp() is defined in firmware/common/include/types.h
    return clamp(normalized, -1.0f, 1.0f);
}

/*
 * floatToPWMCompare(norm)
 *
 * Maps a normalized motor command (-1..+1) to a timer compare register value
 * (0 .. STM32_PWM_PERIOD).
 *
 *   norm = -1.0  →  compare = 0                    (full reverse)
 *   norm =  0.0  →  compare = STM32_PWM_PERIOD / 2  (zero speed)
 *   norm = +1.0  →  compare = STM32_PWM_PERIOD      (full forward)
 *
 * The timer compare register controls PWM duty cycle:
 *   duty = compare / period × 100 %
 *
 * PLACEHOLDER — Same caveat as Arduino version:
 *   TM4 inverters use RS232, not PWM. This maps to a PWM output for bench
 *   testing only. Replace this function body (not the signature) when the
 *   RS232 protocol is documented.
 */
static uint32_t floatToPWMCompare(float norm) {
    float mid    = (float)STM32_PWM_PERIOD * 0.5f;
    float scaled = mid + (norm * mid);    // -1..+1 → 0..PERIOD
    int   cmp    = (int)scaled;
    if (cmp < 0)                    cmp = 0;
    if (cmp > STM32_PWM_PERIOD)     cmp = (int)STM32_PWM_PERIOD;
    return (uint32_t)cmp;
}

// ─────────────────────────────────────────────────────────────────────────────
// Public HAL functions
// ─────────────────────────────────────────────────────────────────────────────

void hal_init() {
    // CubeMX has already run HAL_Init(), SystemClock_Config(), and all
    // MX_*_Init() calls before this function is reached. We only need to:
    //   1. Start the PWM timer channels
    //   2. Assert safe output defaults

    // ── Start PWM timer channels ─────────────────────────────────────────────
    // TIM3 must be started before __HAL_TIM_SET_COMPARE() has any effect.
    // The duty cycle starts at 50% (stopped) due to the compare values below.
    HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_1);   // Left  motor (PB4)
    HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_2);   // Right motor (PB5)

    // ── Safe power-on defaults ────────────────────────────────────────────────
    HAL_GPIO_WritePin(PIN_MOTOR_ENABLE_PORT, PIN_MOTOR_ENABLE_PIN, GPIO_PIN_RESET); // Motors off
    HAL_GPIO_WritePin(PIN_BRAKE_RELAY_PORT,  PIN_BRAKE_RELAY_PIN,  GPIO_PIN_SET);   // Brakes on

    // Set both motor PWM channels to midpoint = zero speed command
    __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_1, STM32_PWM_PERIOD / 2);
    __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_2, STM32_PWM_PERIOD / 2);

    // LEDs off
    HAL_GPIO_WritePin(PIN_LED_IDLE_PORT,   PIN_LED_IDLE_PIN,   GPIO_PIN_RESET);
    HAL_GPIO_WritePin(PIN_LED_MANUAL_PORT, PIN_LED_MANUAL_PIN, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(PIN_LED_FAULT_PORT,  PIN_LED_FAULT_PIN,  GPIO_PIN_RESET);
}

InputSnapshot hal_readInputs() {
    InputSnapshot in;

    // ── Joystick ADC reads ────────────────────────────────────────────────────
    // Each call reconfigures the ADC channel, converts once, and returns.
    // Two calls = ~2 µs total blocking time at 84 MHz — negligible at 100 Hz.
    uint32_t rawThrottle = adc_read_channel(ADC_CHANNEL_0);   // PA0
    uint32_t rawSteering = adc_read_channel(ADC_CHANNEL_1);   // PA1

    in.throttleNorm = normalizeJoystick(rawThrottle);
    in.steeringNorm = normalizeJoystick(rawSteering);

    // ── Digital safety inputs (active-LOW inversion) ───────────────────────
    // GPIO configured as INPUT with internal pull-up in CubeMX.
    // GPIO_PIN_RESET (0) = switch closed = active → we map to true.
    in.estopPressed     = (HAL_GPIO_ReadPin(PIN_ESTOP_PORT,           PIN_ESTOP_PIN)           == GPIO_PIN_RESET);
    in.operatorEnable   = (HAL_GPIO_ReadPin(PIN_OPERATOR_ENABLE_PORT, PIN_OPERATOR_ENABLE_PIN) == GPIO_PIN_RESET);
    in.faultAcknowledge = (HAL_GPIO_ReadPin(PIN_FAULT_ACK_PORT,       PIN_FAULT_ACK_PIN)       == GPIO_PIN_RESET);

    // ── Signal-alive flag ─────────────────────────────────────────────────────
    // Local joystick is always alive. If a Jetson serial link is added later,
    // monitor its last-received timestamp here and set this false on timeout.
    in.inputSignalAlive = true;

    return in;
}

void hal_setMotorEnable(bool enable) {
    HAL_GPIO_WritePin(
        PIN_MOTOR_ENABLE_PORT,
        PIN_MOTOR_ENABLE_PIN,
        enable ? GPIO_PIN_SET : GPIO_PIN_RESET
    );
}

void hal_setBrake(bool apply) {
    // ASSUMPTION: GPIO_PIN_SET = relay energized = brakes APPLIED.
    // Same fail-safe logic as the Arduino version — see hal_arduino.cpp for
    // the full rationale. Flip SET/RESET here if your relay is wired inversely.
    HAL_GPIO_WritePin(
        PIN_BRAKE_RELAY_PORT,
        PIN_BRAKE_RELAY_PIN,
        apply ? GPIO_PIN_SET : GPIO_PIN_RESET
    );
}

void hal_setMotorOutputs(float leftNorm, float rightNorm) {
    // PLACEHOLDER — PWM via TIM3 CH1/CH2 compare registers.
    //
    // __HAL_TIM_SET_COMPARE is a macro that writes directly to the timer's
    // CCR (Capture/Compare Register). It takes effect on the next PWM period
    // (within 1 ms at 1 kHz), so there is no need to stop/restart the timer.
    //
    // FUTURE — RS232 to TM4 inverters:
    //   When the TM4 serial protocol is documented, replace these two macro
    //   calls with serial packet writes over UART (huart1 or huart2).
    //   The rest of the firmware does not change.
    //
    //   Example future body:
    //     tm4_send_speed(TM4_MOTOR_LEFT,  leftNorm,  &huart1);
    //     tm4_send_speed(TM4_MOTOR_RIGHT, rightNorm, &huart1);
    __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_1, floatToPWMCompare(leftNorm));
    __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_2, floatToPWMCompare(rightNorm));
}

void hal_setStatusLED(SystemState state) {
    // HAL_GetTick() is the STM32 equivalent of Arduino's millis().
    // It returns milliseconds since power-on (1 ms SysTick interrupt).
    // The blink logic is identical to the Arduino version.

    bool idleOn   = false;
    bool manualOn = false;
    bool faultOn  = false;

    switch (state) {
        case SystemState::SAFE_IDLE:
            idleOn = true;
            break;

        case SystemState::MANUAL:
            manualOn = true;
            break;

        case SystemState::FAULT:
            faultOn = ((HAL_GetTick() / 250UL) % 2UL) == 0;
            break;

        default:
            {
                bool flash = ((HAL_GetTick() / 100UL) % 2UL) == 0;
                idleOn = manualOn = faultOn = flash;
            }
            break;
    }

    HAL_GPIO_WritePin(PIN_LED_IDLE_PORT,   PIN_LED_IDLE_PIN,   idleOn   ? GPIO_PIN_SET : GPIO_PIN_RESET);
    HAL_GPIO_WritePin(PIN_LED_MANUAL_PORT, PIN_LED_MANUAL_PIN, manualOn ? GPIO_PIN_SET : GPIO_PIN_RESET);
    HAL_GPIO_WritePin(PIN_LED_FAULT_PORT,  PIN_LED_FAULT_PIN,  faultOn  ? GPIO_PIN_SET : GPIO_PIN_RESET);
}
