/*
 * pins_stm32.h — STM32F4 hardware pin assignments for DANA Mower
 *
 * Target board: STM32 Nucleo-F401RE (or Nucleo-F411RE)
 * HAL library:  STM32 HAL (generated by STM32CubeMX)
 *
 * ─── HOW STM32 PINS DIFFER FROM ARDUINO ────────────────────────────────────
 *
 * On Arduino you write:  digitalWrite(7, HIGH);
 * On STM32 you write:    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_0, GPIO_PIN_SET);
 *
 * Every STM32 GPIO has two components:
 *   • Port  — a letter A..E identifying a group of 16 pins (GPIOA, GPIOB, …)
 *   • Pin   — a number 0..15 within that group (GPIO_PIN_0 .. GPIO_PIN_15)
 *
 * This file defines both components for every signal so that hal_stm32.cpp
 * never contains raw port/pin literals — all hardware assignments live here.
 *
 * ─── PERIPHERAL HANDLES ─────────────────────────────────────────────────────
 *
 * STM32 peripherals (ADC, timers, UART) are represented by handle structs
 * (hadc1, htim3, huart2, …) that CubeMX generates in main.c.
 * hal_stm32.cpp uses extern declarations for those handles — they are not
 * listed here because they are not "pins".
 *
 * ─── CUBEMX CONFIGURATION SUMMARY ──────────────────────────────────────────
 *
 * Configure these peripherals in CubeMX before compiling hal_stm32.cpp:
 *
 *   ADC1      IN0 (PA0) + IN1 (PA1) — continuous, scan mode, DMA or polling
 *   TIM3      CH1 (PB4) + CH2 (PB5) — PWM output, 20 kHz, AF2
 *   USART2    PA2 (TX) / PA3 (RX)   — 115 200 baud, for debug serial
 *   GPIO      See table below
 *
 * GPIO configuration table:
 *   Signal            Port  Pin   Mode            Pull       Note
 *   ─────────────────────────────────────────────────────────────────────────
 *   JOY_THROTTLE      PA    0     Analog           None      ADC1_IN0
 *   JOY_STEERING      PA    1     Analog           None      ADC1_IN1
 *   ESTOP             PC    13    Input            Pull-up   Nucleo user button
 *   OPERATOR_ENABLE   PB    0     Input            Pull-up
 *   FAULT_ACK         PB    1     Input            Pull-up
 *   MOTOR_ENABLE      PC    0     Output PP 50MHz  None
 *   BRAKE_RELAY       PC    1     Output PP 50MHz  None
 *   MOTOR_LEFT_PWM    PB    4     AF2 (TIM3_CH1)  None      Timer PWM
 *   MOTOR_RIGHT_PWM   PB    5     AF2 (TIM3_CH2)  None      Timer PWM
 *   LED_IDLE          PC    2     Output PP 50MHz  None
 *   LED_MANUAL        PA    5     Output PP 50MHz  None      LD2 on Nucleo
 *   LED_FAULT         PC    3     Output PP 50MHz  None
 */

#pragma once
#include "stm32f4xx_hal.h"   // STM32F4 HAL master header (adjust for F1/F3/etc)

// ─────────────────────────────────────────────────────────────────────────────
// ANALOG INPUTS — Joystick axes
// (ADC channel selection is done in CubeMX / MX_ADC1_Init, not via these macros)
// ─────────────────────────────────────────────────────────────────────────────
#define PIN_JOY_THROTTLE_PORT   GPIOA
#define PIN_JOY_THROTTLE_PIN    GPIO_PIN_0   // ADC1_IN0

#define PIN_JOY_STEERING_PORT   GPIOA
#define PIN_JOY_STEERING_PIN    GPIO_PIN_1   // ADC1_IN1

// ADC full-scale: 12-bit on STM32F4 = 0–4095.
// Re-use the same DEADBAND + MAX constants (scaled to 12-bit) in hal_stm32.cpp.
#define STM32_ADC_CENTER   2048    // Midpoint (0–4095 scale)
#define STM32_ADC_DEADBAND  160    // ±160 counts around center → zero output
#define STM32_ADC_MAX      1900    // Counts from center to full deflection

// ─────────────────────────────────────────────────────────────────────────────
// DIGITAL INPUTS — Safety switches (active-LOW, internal pull-up)
// ─────────────────────────────────────────────────────────────────────────────
#define PIN_ESTOP_PORT           GPIOC
#define PIN_ESTOP_PIN            GPIO_PIN_13  // Also the blue user button on Nucleo

#define PIN_OPERATOR_ENABLE_PORT GPIOB
#define PIN_OPERATOR_ENABLE_PIN  GPIO_PIN_0

#define PIN_FAULT_ACK_PORT       GPIOB
#define PIN_FAULT_ACK_PIN        GPIO_PIN_1

// ─────────────────────────────────────────────────────────────────────────────
// DIGITAL OUTPUTS — Motor controller enable / brake relay
// ─────────────────────────────────────────────────────────────────────────────
#define PIN_MOTOR_ENABLE_PORT    GPIOC
#define PIN_MOTOR_ENABLE_PIN     GPIO_PIN_0

#define PIN_BRAKE_RELAY_PORT     GPIOC
#define PIN_BRAKE_RELAY_PIN      GPIO_PIN_1

// ─────────────────────────────────────────────────────────────────────────────
// TIMER PWM OUTPUTS — Motor speed commands
//
// TIM3 CH1 = PB4 (AF2), TIM3 CH2 = PB5 (AF2).
// These pins switch to alternate-function mode in CubeMX and are driven by
// the timer, NOT by HAL_GPIO_WritePin — so the PORT/PIN macros are only
// listed here for documentation. The actual PWM write uses __HAL_TIM_SET_COMPARE.
//
// Timer configuration (set in CubeMX):
//   Clock source : APB1 timer clock = 84 MHz (Nucleo-F401RE default)
//   Prescaler    : 83      → timer tick = 1 µs (84 MHz / (83+1) = 1 MHz)
//   Period       : 999     → 1 kHz PWM (1 MHz / (999+1) = 1 kHz)
//   Change Period to 49 for 20 kHz (1 MHz / 50 = 20 kHz) — quieter for motors
//
// hal_stm32.cpp uses TIM_CHANNEL_1 and TIM_CHANNEL_2.
// ─────────────────────────────────────────────────────────────────────────────
#define PIN_MOTOR_LEFT_PORT      GPIOB
#define PIN_MOTOR_LEFT_PIN       GPIO_PIN_4   // TIM3 CH1 AF2

#define PIN_MOTOR_RIGHT_PORT     GPIOB
#define PIN_MOTOR_RIGHT_PIN      GPIO_PIN_5   // TIM3 CH2 AF2

// PWM timer period register value (must match CubeMX Period setting)
#define STM32_PWM_PERIOD         999          // 1 kHz at 1 µs tick

// ─────────────────────────────────────────────────────────────────────────────
// DIGITAL OUTPUTS — Status LEDs
// ─────────────────────────────────────────────────────────────────────────────
#define PIN_LED_IDLE_PORT        GPIOC
#define PIN_LED_IDLE_PIN         GPIO_PIN_2

#define PIN_LED_MANUAL_PORT      GPIOA
#define PIN_LED_MANUAL_PIN       GPIO_PIN_5   // LD2 — onboard green LED on Nucleo

#define PIN_LED_FAULT_PORT       GPIOC
#define PIN_LED_FAULT_PIN        GPIO_PIN_3
